from number_of_inversions_py.brute_force import count_num_inversions
from number_of_inversions_py.count_split_inversions import CountSplitInversions
from number_of_inversions_py.count_num_of_inversions import CountNumOfInversions